project:
  type: book
  output-dir: docs

book:
  title: "金融数据获取、管理与初步分析"
  author: "吴思雨25210090"
  chapters:
    - index.qmd
    - 01-introduction.qmd
    - 02-data-download.qmd
    - 03-data-cleaning.qmd
    - 04-analysis.qmd
    - 05-conclusion.qmd

format:
  html:
    number-sections: true
